#define	DLG_ABOUT                   100
#define DLG_ABOUT_ICON              101
#define DLG_ABOUT_TEXT              102
#define	DLG_ABOUT_OK                103

#define DLG_OPTIONS                 200
#define DLG_REFRESHGRP              201
#define DLG_INTERVAL                202
#define DLG_INTERVALTXT             203
#define DLG_SECSTXT                 204
#define DLG_OPTIONS_UNDO            205
#define DLG_OPTIONS_DEFAULT         206
#define DLG_OPTIONS_HELP            207
#define DLG_METHOD                  208
#define DLG_METHOD_SWAPFILE         209		/* SWAPFILE, TIMER and DRIVER must be... */
#define DLG_METHOD_TIMER            210
#define DLG_METHOD_DRIVER           211		/* ...contiguous and in this order */

#define DLG_WATCH                   300
#define DLG_WATCHTEXT               301
