/*
 * File: helpdefs.h
 *
 * Class for Workplace Shell uptime monitor.
 *
 * Help definition file
 *
 * Bob Eager   October 2004
 *
 */

/* IDs for help panels */

#define	HLP_GENERAL		1000
#define	HLP_SETUP		1001
#define	HLP_AUTHOR		1002

#define	HLP_OPTIONS		1010
#define	HLP_OPTIONS_REFRESH	1011
#define	HLP_OPTIONS_METHOD	1012
#define	HLP_DRIVER		1013
#define	HLP_DRIVER_PROG		1014
#define	HLP_TITLE_TEXT		1015

#define	HLP_WATCH		1100
#define	HLP_CLOSEVIEW		1101
#define	HLP_ABOUT		1102

#define	HLP_K_REFRESH_INTERVAL	1200
#define	HLP_K_UPTIME_METHOD	1201

/*
 * End of file: helpdefs.h
 *
 */
